### ISSUE TITLE
getMessage() possible?

### ISSUE THREAD

**Issue by janwalther** [shrikeh/teapot#27]
I like the way teapot uses interfaces to follow the open-closed-principle of SOLID (when new HTTP codes are "invented", no old code will have to be modified). But one thing I am missing: a function to get the message belonging to a given code (e.g. return "Not Found" for 404).
As PHP does (thankfully) not support multiple inheritence I do not see a way to deliver the status messages within the same unit (interface / class) as the response code constants. This would mean to have a separate repository class which could translate the response codes to the belonging messages but this would contradict the modular structure of teapot (because this class would have to contain a list of all HTTP status messages).

What do you think? Is such a getMessage() function possible in a clean way?

**Comment by shrikeh** [comment]
This is an interesting one, because the actual text of a status code is not, as I understand, part of the RFC. That is, you are allowed to return 404 and have the accompanying message in German, for example. Nothing, as far as I am aware, states that the message must be in English. However, the status codes do by convention always seem to have standardised text accompanying them in most, if not all, documentation.

However, status codes themselves are not unique: an example is that Twitter uses ENHANCE_YOUR_CALM (420) for API usage, while 420 in PEP is for POLICY_NOT_FULFILLED. Determining the correct status text to return would also require passing a context.

My suggestion would be simply a YAML file with the status codes as a key and the preferred message as the value, and then do a simple lookup. The advantage would be that you could decide what status codes your system is expected to return, and if a code is tried that is not known, you can have a word with the developer and say "hey, why are we returning 420 for this?"

**Comment by janwalther** [comment]
Oh, you are right, messages are only a recommendation.

[RFC 7231](http://tools.ietf.org/html/rfc7231#section-6.1) says: 
> The reason phrases listed here are only recommendations
> -- they can be replaced by local equivalents without affecting the
> protocol."

**Comment by janwalther** [comment]
Ok, messages are not really a problem (nevertheless it would be nice to get the ones recommended in the RFC).
But another thing is not optional: Which status codes are allowed to have a body. E.g. all 1xx, 204 and 304 are not allowed to have a body. But again this is hard to implement when only using interfaces. Any ideas on this? I imagine a method canHaveBody() which returns a boolean value.

Sure you could implement this check, whether the status code allows a body, in a HTTPMessage class which uses teapot for handling status codes but I understand teapot as a value object which encapsulates everything about status codes.

**Comment by shrikeh** [comment]
Sounds to me as if we need a small class that knows a bit more about the RFCs... Do you want to come up with something and PR it, or would you like me to?









—

**Comment by shrikeh** [comment]
Actually, I've had a bit of a brainwave. Allow me to have a go, and then please review.



—

**Comment by janwalther** [comment]
Of course I will review your idea...

But I would also like to publish my idea. As said above I thought about a method HTTPStatus::isAllowedtoHaveBody(). This seems strange to me because a HTTP status can never have a body but a HTTP message can. This lead me to the following: We have to extend teapot to a larger scope. Instead of just handling status codes, we would need to handle a complete HTTP server response. And then the method HTTPResponse::isAllowedtoHaveBody() would make sense.
My first idea to implement this has been to implement the [PSR-7 ServerResponse Interface](https://github.com/php-fig/fig-standards/blob/master/proposed/http-message.md#33-psrhttpmessageresponseinterface) in an abstract HttpResponse class and extend this class with status code classes, e.g.
```php
namespace teapot;

abstract class HttpResponse implements Psr\Http\Message\ResponseInterface {
  ...
  public function withBody(StreamableInterface $body) {
    if($this->isAllowedToHaveBody()) {
      throw new \DomainException('A '.get_class($this).' object is not allowed to have a body');
    }
    $that = clone $this;
    $that->setBody($body);
    return $that;
  }
  ...

  abstract public function isAllowedToHaveBody();
}

namespace teapot\rfc2616;
class HttpOK extends HttpResponse {
  public function isAllowedToHaveBody() {
    return true;
  }

  public function getStatusCode() {
    return 200;
  }

  public function getReasonPhrase() {
    return 'OK';
  }
}
```

This way the Open-close principle works as before: when a new RFC gets published, new classes can be written which extend our HttpResponse base class -> no old code would have to be touched.

At first I doubted if this solution would fulfill the Liskov substitution principle. But in my opionion it does (in contrast of overwriting the withBody() method in the child classes -> the latter would break LSP).

And as you mentioned especially vendor-specific status codes are not unique. This would be no problem. Even if the class names would be the same, I would recommend to put them in different namespaces (regarding the vendor which "invented" this status code). 

What do you think of this idea?
But I am am also really looking forward to your solution...

**Comment by janwalther** [comment]
Any news on this topic?

**Comment by shrikeh** [comment]
Hi Jan,

hectic at work due to dealing with GHOST and a few other things. I’m going to take a look this weekend, if not before. Haven’t forgotten this, just trying to squeeze in hours is tricky atm!  

--  
Barney Hanlon
Software Engineer
+44 7702 271 484
about.me (http://about.me/barneyhanlon)
@shrikeh

**Comment by shrikeh** [comment]
Having thought about it, the "beauty" of Teapot is that is has no opinions, no code, etc. It is purely a nice way to add verbosity to response codes. There's absolutely nothing wrong with taking Teapot and adding additional functionality on top of it, but I think I like the fact that all it is is a list of response codes to aid legibility in other components. I think I'm going to keep it as is, but I would very much like to see what you come up with.
